spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://rubberdu.postgres.database.azure.com:5432/postgres
    username: RubberDuck@rubberdu
    password: 12345678Aa
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
